name: Test Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Replace tokens in .tfvars and .tf
        # You may pin to the exact commit or the version.
        # uses: cschleiden/replace-tokens@4d5a042c84c3568b3858b7af9394923d2d5195c9
        uses: cschleiden/replace-tokens@v1.3
        with:
          # # 
          # tokenPrefix: # optional, default is #{
          # # 
          # tokenSuffix: # optional, default is }#
          # 
          files: 
            - terraform-research.auto.tfvars
            - terraform-connectivity.auto.tfvars
            - terraform.tfvars
            - main.tf
            # optional, default is #{
      
      - name: Cat TFvars file
        run: |
          echo "cat tfvars file"
          cat terraform.tfvars
