name: Test Workflow

on:
  # workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Replace tokens in .tfvars and .tf
        # You may pin to the exact commit or the version.
        # uses: cschleiden/replace-tokens@4d5a042c84c3568b3858b7af9394923d2d5195c9
        uses: qetza/replacetokens-action@v1
        id: replace-tokens
        with:
          # root: /home/runner/work/terraform-ca-foundation/terraform-ca-foundation/germanywestcentral/dev
          root: "${{ github.workspace }}/terraform-ca-foundation/germanywestcentral/dev"
          
          sources: |
            terraform.tfvars
          missing-var-action: none
          missing-var-log: warn
          log-level: 'debug'
          variables: >
            {
              "LOCATION": "${{ env.LOCATION }}",
              "ENVIRONMENT": "${{ env.ENVIRONMENT }}"
            }
            
      - run: |
          echo "defaults  : ${{ steps.replace-tokens.outputs.defaults }}"
          echo "files     : ${{ steps.replace-tokens.outputs.files }}"
          echo "replaced  : ${{ steps.replace-tokens.outputs.replaced }}"
          echo "tokens    : ${{ steps.replace-tokens.outputs.tokens }}"
          echo "transforms: ${{ steps.replace-tokens.outputs.transforms }}"

      - run: |
          pwd
          cat /home/runner/work/terraform-ca-foundation/terraform-ca-foundation/germanywestcentral/dev/terraform.tfvars
          ls -la /home/runner/work/terraform-ca-foundation/terraform-ca-foundation/germanywestcentral/dev
          du --max-depth=5 -h
          cat "${{ github.workspace }}/germanywestcentral/dev/terraform.tfvars"
          

