name: All-in-One_Pipeline

on:
  workflow_dispatch:
    inputs:
      Action:
        description: 'Terraform Action'
        required: true
        default: 'Create'
        type: choice
        options: 
          - create
          - destroy
      Environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      Location:
        description: 'Azure Region'
        required: true
        default: 'germanywestcentral'
        type: choice
        options:
          - germanywestcentral
          - westeurope

jobs:
  tf_plan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.Environment }}
    env:
      ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
    #   ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    #   ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    #   ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    #   ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    #   TFSTATE_RG: ${{ secrets.TFSTATE_RG }}
    #   TFSTATE_STORAGE: ${{ secrets.TFSTATE_STORAGE }}
    #   TFSTATE_CONTAINER: ${{ secrets.TFSTATE_CONTAINER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace tokens in .tfvars and .tf
        uses: qetza/replacetokens-action@v1
        id: replace-tokens
        with:
          root: "${{ github.workspace }}/${{ inputs.Location }}/${{ inputs.Environment }}"
          
          sources: |
            *.tfvars
            providers.tf
          missing-var-action: none
          missing-var-log: warn
          log-level: 'debug'
          variables: >
            [
              ${{ toJSON(vars) }},
              ${{ toJSON(secrets) }}
            ]

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        working-directory: "${{ github.workspace }}/${{ inputs.Location }}/${{ inputs.Environment }}"
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ vars.TFSTATE_RG }}" \
            -backend-config="storage_account_name=${{ vars.TFSTATE_STORAGE }}" \
            -backend-config="container_name=${{ vars.TFSTATE_CONTAINER }}" \
            -backend-config="key=${{ vars.TFSTATE_KEY }}" \
            -var="client_id=${{ secrets.ARM_CLIENT_ID }}" \
            -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
            -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" \
            -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}"

      - name: Terraform Validate
        working-directory: "${{ github.workspace }}/${{ inputs.Location }}/${{ inputs.Environment }}"
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: "${{ github.workspace }}/${{ inputs.Location }}/${{ inputs.Environment }}"
        run: |    
          # PLAN_FILE="${{ inputs.Action }}-${{ github.workflow }}-${{ github.run_number }}.tfplan"
          if [[ "${{ inputs.Action }}" == "Destroy" ]]; then
            terraform plan -destroy -out $PLAN_FILE \
              -var="client_id=${{ secrets.ARM_CLIENT_ID }}" \
              -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
              -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" \
              -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}"
          else
            terraform plan -out $PLAN_FILE \
              -var="client_id=${{ secrets.ARM_CLIENT_ID }}" \
              -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
              -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" \  
              -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}"
          fi
        
        # PLAN_FILE="${{ github.workflow }}-${{ github.run_number }}.tfplan"
        # terraform plan \
          # -var="client_id=${{ secrets.ARM_CLIENT_ID }}" \
          # -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
          # -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" \
          # -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}"
    
        # - name: Upload tfplan as artifact
        #   uses: actions/upload-artifact@v4
        #   with:
        #     name: Terraform_Plan
        #     path: ${{ inputs.WorkingDirectory }}/${{ github.workflow }}-${{ github.run_number }}.tfplan
