name: My-TF-Deploy-Workflow 

on:
  workflow_dispatch:
    inputs:
      Action:
        description: 'Terraform Action'
        required: true
        default: 'Create'
        type: choice
        options: 
          - Create
          - Destroy
      Environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      Location:
        description: 'Azure Region'
        required: true
        default: 'germanywestcentral'
        type: choice
        options:
          - germanywestcentral
          - westeurope

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  tf_plan:
    uses: ./.github/workflows/tf-plan.yml
    with:
      Action: ${{ github.event.inputs.Action }}
      Environment: ${{ github.event.inputs.Environment }}
      Location: ${{ github.event.inputs.Location }}

  # approval:
  #   needs: tf_plan
  #   environment: ${{ github.event.inputs.Environment }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Approval Required
  #       run: echo "Waiting for approval..."

  approval_gate:
    name: Await Manual Approval
    runs-on: ubuntu-latest
    needs: tf_plan
    environment:
      name: prod          # <-- окружение с approval reviewer'ами
      url: https://portal.azure.com  # можно указать ссылку на портал или Pull Request
    steps:
      - name: Wait for Approval
        run: echo "Waiting for manual approval..."

  # tf_apply:
  #   needs: approval
  #   uses: ./.github/workflows/tf-apply.yml
  #   with:
  #     Action: ${{ github.event.inputs.Action }}
  #     Environment: ${{ github.event.inputs.Environment }}
  #     Location: ${{ github.event.inputs.Location }}